[build]
  command = "npm run build"
  publish = "dist"

[functions]
  included_files = [
    "src/templates/report-template.html", 
    "src/scripts/raport_logic.js",
    "public/fonts/*.ttf"
  ]

# TO NAPRAWI BŁĄD 404
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200