[build]
  command = "npm run build"
  publish = "dist"

[functions]
  # directory = "netlify/functions"
  
  # ZMIANA: Wskazujemy na folder public/fonts
  included_files = [
    "src/templates/report-template.html", 
    "src/scripts/raport_logic.js",
    "public/fonts/*.ttf"
  ]